'use client';

import { useCallback, useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { CLASS_LABEL, fmt } from '../vendor/shared/src';

interface Card {
  symbol: string;
  name: string;
  assetClass: string;
  decimals: number;
  price: number;
  changePct24h: number | null;
  bias: 'bullish' | 'bearish' | 'neutral';
  composite: number;
  confidence: number;
  regime: string;
  updatedAt: number;
  source: 'yahoo' | 'synthetic';
  error?: string;
}

const CLASS_ORDER = ['index', 'commodity', 'forex', 'crypto'];

function timeAgo(ts: number): string {
  const s = Math.max(0, Math.round((Date.now() - ts) / 1000));
  if (s < 60) return `${s}s ago`;
  return `${Math.round(s / 60)}m ago`;
}

function scoreColor(bias: string) {
  return bias === 'bullish' ? 'bullish' : bias === 'bearish' ? 'bearish' : 'neutral';
}

export default function OverviewPage() {
  const [cards, setCards] = useState<Card[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const router = useRouter();

  const load = useCallback(async () => {
    try {
      const res = await fetch('/api/instruments', { cache: 'no-store' });
      if (!res.ok) throw new Error(`API ${res.status}`);
      const j = (await res.json()) as { instruments: Card[] };
      setCards(j.instruments);
      setError(null);
    } catch (e) {
      setError(e instanceof Error ? e.message : 'failed to load');
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    load();
    const id = setInterval(load, 60_000);
    return () => clearInterval(id);
  }, [load]);

  const bulls = cards.filter((c) => c.bias === 'bullish').length;
  const bears = cards.filter((c) => c.bias === 'bearish').length;
  const neutrals = cards.length - bulls - bears;
  const anySynthetic = cards.some((c) => c.source === 'synthetic');

  return (
    <div>
      <div className="header-line">
        <h1>Market Overview</h1>
        {!loading && (
          <>
            <span className="badge bullish">{bulls} bullish</span>
            <span className="badge bearish">{bears} bearish</span>
            <span className="badge neutral">{neutrals} neutral</span>
            {anySynthetic && <span className="badge dim">simulated feed on some symbols</span>}
          </>
        )}
      </div>

      {error && <div className="error-box">Failed to load instruments: {error}</div>}
      {loading && <div className="skeleton">Loading market data…</div>}

      {CLASS_ORDER.map((cls) => {
        const group = cards.filter((c) => c.assetClass === cls);
        if (!group.length) return null;
        return (
          <section key={cls}>
            <div className="section-title">{CLASS_LABEL[cls as keyof typeof CLASS_LABEL]}</div>
            <div className="tiles">
              {group.map((c) => (
                <div
                  key={c.symbol}
                  className={`tile ${scoreColor(c.bias)}`}
                  onClick={() => router.push(`/markets/${c.symbol}`)}
                >
                  <div className="row">
                    <div>
                      <div className="sym">{c.symbol}</div>
                      <div className="name">{c.name}</div>
                    </div>
                    <span className={`badge ${scoreColor(c.bias)}`}>{c.bias}</span>
                  </div>
                  <div className="row">
                    <div className="price num">{c.price ? fmt(c.price, c.decimals) : '—'}</div>
                    {c.changePct24h != null && (
                      <div className={`chg num ${c.changePct24h >= 0 ? 'up' : 'down'}`}>
                        {c.changePct24h >= 0 ? '▲' : '▼'} {Math.abs(c.changePct24h).toFixed(2)}%
                      </div>
                    )}
                  </div>
                  <div className={`scorebar ${scoreColor(c.bias)}`}>
                    <span style={{ width: `${c.composite}%` }} />
                  </div>
                  <div className="meta">
                    <span>
                      score <b className="num">{c.composite.toFixed(0)}</b> · conf{' '}
                      <b className="num">{c.confidence}%</b>
                    </span>
                    <span>
                      {c.regime}
                      {c.source === 'synthetic' ? ' · sim' : ''} · {timeAgo(c.updatedAt)}
                    </span>
                  </div>
                </div>
              ))}
            </div>
          </section>
        );
      })}

      <p className="footer-note">
        Signals are generated by the deterministic engine (TA + Smart Money Concepts) from live 5-minute
        data; AI narratives and WhatsApp alerting arrive in later milestones. Educational analysis only —
        not financial advice. Index data may be delayed by the provider.
      </p>
    </div>
  );
}
